name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain ${{ matrix.channel }}
        run: |
          rustup set profile minimal
          rustup update --no-self-update $RUST_CHANNEL
          rustup component add --toolchain $RUST_CHANNEL rustfmt clippy
        env:
          RUST_CHANNEL: ${{ matrix.channel }}
      - run: cargo build
      - run: cargo test
      - run: cargo clippy --all-targets --all-features -- --deny warnings
